### ISSUE TITLE
Behaviour of SMA when window size > init length

### ISSUE THREAD

**Issue by THargreaves** [THargreaves/onlineoceanarium#8]
When the window size is greater than the initialisation vector length as in `SMA$new(c(1, 2), window=3)` the values vector is padded on the left with zeros so that `SMA$value()` is 1 rather than 1.5 initially. Is this intended behaviour? If so, it might be worth adding that to the docs.

**Comment by Kaasiak** [comment]
Well spotted. When thinking about this now I guess is should not be the case. In the case you described 1.5 is the value of the mean which I would expect. Will correct this.

**Comment by Kaasiak** [comment]
Fixed with 1c4a8deaef9b3c2b352e2a67558f1093253f6e80
